# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 95dc72f7ab6a70d20446159c0d9dd093656aa5163d8504ac2bd1514ad3c96675baf9cd2f5937220dd837f482c658cceba80cfbd28a87ec2839fe78de1bfde159

test:
  secret_key_base: 85ec44f471f61077458fbd6ad118a23c487ed7bb91621dcf165912e3c69d434cceed208cf1f81e91f74e039049dcad757db76e79f661c24dbc70c4ba469b8354

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
